### ISSUE TITLE
Ready to share?

### ISSUE THREAD

**Issue by lucasbledsoe** [intive-opensource/adyen_flutter#1]
Hi There,

I work for Adyen and we think it's awesome you are building a flutter project about Adyen. Do you mind if we share about this repo in our next newsletter?

Best,
Lucas

**Comment by bennibau** [comment]
When will this be? I want to update the deps to the most recent adyen version and I need to update the readme first

**Comment by lucasbledsoe** [comment]
We have a newsletter slated for Feb 25th/26th otherwise the next one will be end of March.

**Comment by bennibau** [comment]
@lucasbledsoe Okay we will update the readme and version of adyen SDK today so you can include this in the newsletter tomorrow if you want.

**Comment by bennibau** [comment]
the package was now published on pub.dev

**Comment by bennibau** [comment]
https://pub.dev/packages/adyen_dropin
